slug: "cups"
name: "CUPS"
description: "Enables printer sharing across LAN"
version: "0.9.0"
init: false
host_network: true
usb: true

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

map:
  - share:rw

ports:
  631/tcp: 631
  631/udp: 631

startup: services

schema:
  on_startup: list(Start CUPS|Reset CUPS|Reset configuration)?
